export function mountMessages({client,addPanel,addAdmin,nav,show,action,status}){
 const el=(tag,text='')=>{const x=document.createElement(tag);x.textContent=text;return x},read=async q=>{const {data,error}=await q;if(error)throw error;return data};
 const panel=addPanel('messages','Messages',`<div class="card"><h2>Messages</h2><p>Private conversations with GAC. Messages stay saved in your account.</p><div id="messageOwnerTools" hidden><h3>Your member inbox</h3><div id="messageInbox"></div></div><div class="message-chat"><button id="messageBack" type="button" class="secondary" hidden>← Back to inbox</button><h3 id="messageTitle">GAC · Private conversation</h3><p id="messageStatus" class="small" role="status">Updates automatically while you are signed in.</p><button id="messageOlder" type="button" class="secondary" hidden>Load earlier messages</button><div id="messageHistory" class="message-history" role="log" aria-label="Private messages" aria-live="polite"></div><form id="messageForm"><label for="messageBody">Your message</label><textarea id="messageBody" maxlength="2000" required placeholder="Message GAC…"></textarea><button id="messageSend">Send message</button></form></div></div>`);
 const $=id=>panel.querySelector('#'+id),button=nav.querySelector('[data-panel="messages"]');
 const alias=addAdmin('messages','Messages','<div class="card"><h2>Member messages</h2><p>Read and reply to private conversations with members.</p></div>');const openInbox=el('button','Open member inbox');openInbox.type='button';openInbox.onclick=()=>show('messages');alias.querySelector('.card').append(openInbox);
 const css=el('style');css.textContent='.message-chat{border-top:1px solid #35473b;margin-top:22px;padding-top:15px}.message-history{max-height:520px;overflow:auto;display:flex;flex-direction:column;gap:16px;padding:12px 2px;scrollbar-gutter:stable}.message-row{max-width:85%;align-self:flex-start}.message-row.mine{align-self:flex-end}.message-bubble{padding:14px 17px;border-radius:12px;background:#1b2920;border:1px solid #35473b;white-space:pre-wrap;overflow-wrap:anywhere;line-height:1.5}.message-row.mine .message-bubble{background:#345640;border-color:#516f58}.message-meta{font-size:12px;color:#b7c3bb;margin-top:6px}.message-inbox-row{display:flex;align-items:center;justify-content:space-between;gap:15px;width:100%;text-align:left;padding:16px 12px;margin:0;background:transparent;border:0;border-bottom:1px solid #35473b;border-radius:0}.message-inbox-row.unread{background:#1b2c20}.message-inbox-row .small{flex:1;overflow-wrap:anywhere;color:#b7c3bb}.message-new{flex-shrink:0;color:#c9dcc2;font-size:12px}.message-inbox-row button{margin:0}.message-inbox-row .small{margin:5px 0}@media(max-width:600px){.message-row{max-width:95%}.message-inbox-row{flex-wrap:wrap}.message-history{max-height:420px}}';document.head.append(css);
 let profile=null,owner=false,thread=null,people=[],rows=[],epoch=0,loading=false,olderAvailable=false,signature='',inboxSignature='',opened=false;
 function unread(m){return owner?m.sender_kind==='member'&&!m.owner_read_at:m.sender_kind!=='member'&&!m.member_read_at}
 function clear(){epoch++;profile=null;owner=false;thread=null;people=[];rows=[];signature='';inboxSignature='';opened=false;$('messageBody').value='';$('messageHistory').replaceChildren();$('messageInbox').replaceChildren();button.textContent='Messages';$('messageOwnerTools').hidden=true;}
 async function sync(p,isOwner,members=[]){if(profile?.user_id!==p.user_id||owner!==isOwner)clear();profile=p;owner=isOwner;people=members;$('messageOwnerTools').hidden=!owner;if(owner){thread=people.some(m=>m.user_id===thread)?thread:null;}else thread=p.user_id;render();await refresh();}
 async function markRead(){if(!opened||panel.hidden||document.hidden||!profile)return;const ids=rows.filter(unread).map(m=>m.id).slice(-100);if(!ids.length)return;await read(client.rpc('gac_mark_messages_read',{p_ids:ids}));for(const m of rows)if(ids.includes(m.id))m[owner?'owner_read_at':'member_read_at']=new Date().toISOString();}
 function render(){$('messageOwnerTools').hidden=!owner||!!thread;panel.querySelector('.message-chat').hidden=owner&&!thread;$('messageBack').hidden=!owner;const who=people.find(p=>p.user_id===thread);$('messageTitle').textContent=owner?(who?who.callsign+' · Private conversation':'Choose a member to open a conversation'):'GAC · Private conversation';$('messageBody').placeholder=owner?'Reply to '+(who?.callsign||'member')+'…':'Message GAC…';$('messageSend').disabled=!thread;$('messageBody').disabled=!thread;$('messageOlder').hidden=!olderAvailable;const history=$('messageHistory'),nearBottom=history.scrollHeight-history.scrollTop-history.clientHeight<70,oldTop=history.scrollTop;history.replaceChildren();if(!rows.length)history.append(el('p',thread?'No messages yet. Send a message to start the conversation.':'Select a conversation above.'));for(const m of rows){const mine=owner?m.sender_kind==='gac':m.sender_kind==='member';const row=el('div');row.className='message-row'+(mine?' mine':'');const bubble=el('div',m.body);bubble.className='message-bubble';const label=m.sender_kind==='system'?'GAC · Recognition notification':mine?'You':m.sender_kind==='gac'?'GAC':who?.callsign||'Member';const meta=el('div',label+' · '+new Date(m.created_at).toLocaleString());meta.className='message-meta';row.append(bubble,meta);history.append(row)}history.scrollTop=nearBottom?history.scrollHeight:oldTop;}
 async function loadThread(older=false){if(!thread||!profile){rows=[];render();return}const token=epoch,uid=profile.user_id,id=thread;let query=client.from('gac_messages').select('*').eq('member_id',id).order('created_at',{ascending:false}).order('id',{ascending:false}).limit(50);if(older&&rows.length){const oldest=rows[0];query=query.or('created_at.lt.'+oldest.created_at+',and(created_at.eq.'+oldest.created_at+',id.lt.'+oldest.id+')')};const data=await read(query);if(token!==epoch||profile?.user_id!==uid||thread!==id)return;if(older||!rows.length)olderAvailable=data.length===50;const merged=new Map(rows.map(m=>[m.id,m]));for(const m of data)merged.set(m.id,m);rows=[...merged.values()].sort((a,b)=>a.created_at.localeCompare(b.created_at)||a.id.localeCompare(b.id));const next=JSON.stringify(rows);if(next!==signature){signature=next;render()}await markRead();}
 async function refresh(){if(!profile||loading||document.hidden)return;loading=true;const token=epoch;try{if(owner){const inbox=await read(client.rpc('gac_message_inbox'));inbox.sort((a,b)=>(Number(b.unread_count)>0)-(Number(a.unread_count)>0)||b.last_at.localeCompare(a.last_at));if(token!==epoch)return;const next=JSON.stringify(inbox);if(next!==inboxSignature){inboxSignature=next;$('messageInbox').replaceChildren();if(!inbox.length)$('messageInbox').append(el('p','Messages from members will appear here. New messages appear at the top.'));for(const t of inbox){const row=el('button');row.type='button';row.className='message-inbox-row'+(Number(t.unread_count)>0?' unread':'');row.onclick=()=>choose(t.member_id);row.setAttribute('aria-label','Open conversation with '+t.callsign+(Number(t.unread_count)>0?', '+t.unread_count+' new messages':''));const name=el('strong',t.callsign);const preview=el('span',t.last_body.slice(0,75)+(t.last_body.length>75?'…':''));preview.className='small';const marker=el('span',Number(t.unread_count)>0?'✉ NEW · '+t.unread_count:'View conversation');marker.className='message-new';row.append(name,preview,marker);$('messageInbox').append(row)}}}if(opened&&!panel.hidden)await loadThread();const count=await read(client.rpc('gac_message_unread_count'));if(token!==epoch)return;button.textContent='Messages'+(Number(count)>0?' · '+count:'');$('messageStatus').textContent='Connected · Messages update automatically.';}catch(e){if(token===epoch)$('messageStatus').textContent='Messages could not refresh: '+(e.message||'Please retry.');}finally{loading=false}}
 async function choose(id){epoch++;thread=id;rows=[];signature='';olderAvailable=false;$('messageBody').value='';render();await action(async()=>{await loadThread();await refresh()})}
 $('messageBack').onclick=()=>choose(null);
 $('messageOlder').onclick=()=>action(()=>loadThread(true));
 $('messageForm').onsubmit=e=>{e.preventDefault();return action(async()=>{if(!profile||!thread)throw Error('Choose a conversation first');const body=$('messageBody').value.trim();if(!body)throw Error('Enter a message');const token=epoch;await read(client.rpc('gac_send_message',{p_member_id:thread,p_body:body}));if(token!==epoch)return;$('messageBody').value='';await loadThread();await refresh();status('Message sent and saved.');})};
 setInterval(()=>refresh(),5000);
 return {sync,clear,async open(){opened=true;await refresh()},enforce(){if(!thread)$('messageSend').disabled=true;}};
}
